[package]
name = "pingu"
version = "0.1.0"
authors = ["Jenn Wheeler <jwheeler@antiochcollege.edu>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
crossbeam = "0.7.1"
clap = "2.32.0"
failure = "0.1.5"
pnet = "0.21.0"
pnet_macros_support = "0.21.0"
